FROM node:14

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install


COPY . . 
COPY .env.production .env

RUN npm build

EXPOSE 8080
CMD [ "node", "dist/index.js"]
USER node